# Generated by Django 5.0.7 on 2025-01-06 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='profile_pic/default.jpg', upload_to='profile_pic/')),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('None', 'None')], default='None', max_length=7)),
                ('phone_number', models.CharField(blank=True, default='', max_length=11)),
                ('experience_level', models.CharField(blank=True, choices=[('fresh', 'Fresh'), ('junor', 'Junior'), ('intermediate', 'Intemediate'), ('senior', 'Senior')], default='fresh', max_length=20)),
                ('address', models.CharField(blank=True, default='', max_length=400)),
                ('password_reset_token', models.CharField(blank=True, default='', max_length=60)),
                ('password_reset_expire', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
