# Generated by Django 5.0.7 on 2025-01-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password_reset_token',
        ),
        migrations.AddField(
            model_name='profile',
            name='password_reset_otp',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
