# Generated by Django 5.0.7 on 2025-01-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_profile_password_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('Fresh', 'Fresh'), ('Junior', 'Junior'), ('Intermediate', 'Intemediate'), ('Senior', 'Senior'), ('Lead', 'Lead'), ('Manager', 'Manager')], default='Fresh', max_length=20),
        ),
    ]
