# Generated by Django 5.0.7 on 2025-01-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(default='default_task.jpg', upload_to='task_images'),
        ),
    ]
