# Generated by Django 5.0.7 on 2025-01-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(default='task_images/default_task.png', upload_to='task_images'),
        ),
    ]
